[project]
name = "mini-vit"
version = "0.1.0"
description = "small ViT model"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
main = "main:main"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
